### ISSUE TITLE
Some issue about tensorflow

### ISSUE THREAD

**Issue by YueyuanKang** [4AI/AGN#3]
![image](https://user-images.githubusercontent.com/77316342/139301349-e55a4ea3-1276-40d7-bf57-030cdebde107.png)
when I try to train the model. It always shows an error "AttributeError: module 'TensorFlow.python.framework.ops' has no attribute '_TensorLike'"
And I have installed the version you mention in the README file.

**Comment by SeanLee97** [comment]
@YueyuanKang What's Keras version do you use? To be compatible with TF 1.x, you'd better install `Keras<=2.3.1`. My environment is as follows:

```bash
$pip list | egrep "tensorflow|Keras"
Keras                            2.3.1
Keras-Applications               1.0.8
Keras-Preprocessing              1.1.0
tensorflow                       1.15.0
tensorflow-estimator             1.15.1
```

**Comment by YueyuanKang** [comment]
thanks， solved
